name: build
on: push
jobs:
  windows:
    strategy:
      fail-fast: false
      matrix:
        version: [2019, 2022, 2025]
    runs-on: windows-${{ matrix.version }}
    steps:
    - uses: actions/checkout@v4
      with:
        submodules : recursive
    - run: .\compile\build.bat notest
    - run: .\compile\build.bat copy_script
    - run: .\build\msvc\bin\bootstrap.exe .\bee.lua\test\test.lua -v
    - run: .\luamake.exe version
  ubuntu:
    strategy:
      fail-fast: false
      matrix:
        version: [20.04, 22.04, 24.04]
    runs-on: ubuntu-${{ matrix.version }}
    steps:
    - uses: actions/checkout@v4
      with:
        submodules : recursive
    - run: sudo apt install -y libreadline-dev ninja-build
    - run: sudo apt install -y binutils-dev libunwind-dev
    - run: ./compile/build.sh
    - run: ./luamake version
  macos:
    strategy:
      fail-fast: false
      matrix:
        version: [12, 13, 14]
    runs-on: macos-${{ matrix.version }}
    steps:
    - uses: actions/checkout@v4
      with:
        submodules : recursive
    - run: brew install ninja
    - run: ./compile/build.sh
    - run: ./luamake version
